http:
  routers:
    gitea-rtr:
      rule: "Host(`gitea.{{env "DOMAINNAME"}}`)"
      entryPoints: 
        - websecure-internal
          #- websecure-external
      middlewares:
        - chain-no-auth@file
      service: gitea-svc
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
  services:
    gitea-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "CONTROL_LAN_IP"}}:3000/"

