http:
  routers:
    plex-rtr:
      rule: "Host(`plex.{{env "DOMAINNAME"}}`)"
      entryPoints: 
        - websecure-internal
        - websecure-external
      middlewares:
        - chain-no-auth@file
      service: plex-svc
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
  services:
    plex-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "MEDIA_LAN_IP"}}:32400/"

