http:
  routers:
    overseer-rtr:
      rule: "Host(`overseer.{{env "DOMAINNAME"}}`)"
      entryPoints: 
        - websecure-internal
        - websecure-external
      middlewares:
        - chain-no-auth@file
      service: overseer-svc
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
  services:
    overseer-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "MEDIA_LAN_IP"}}:5055/"

