http:
  routers:
    nextcloud-rtr:
      rule: "Host(`nextcloud.{{env "DOMAINNAME"}}`)"
      entryPoints: 
        - websecure-internal
        - websecure-external
      middlewares:
        - chain-nextcloud@file
      service: nextcloud-svc
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
  services:
    nextcloud-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "MEDIA_LAN_IP"}}:8383/"

