http:
  routers:
    karakeep-rtr:
      rule: "Host(`karakeep.{{env "DOMAINNAME"}}`)"
      entryPoints: 
        - websecure-internal
        - websecure-external
      middlewares:
        - chain-authelia@file
      service: karakeep-svc
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
  services:
    karakeep-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "MEDIA_LAN_IP"}}:3000/"

