services:
  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    security_opt:
      - no-new-privileges:true
    restart: "always"
    profiles: ["aps", "all"]
    networks:
      - default
        #command: -H tcp://socket-proxy:2357
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_INCLUDE_RESTARTING: true
      WATCHTOWER_POLL_INTERVAL: 36000
