services:
  nextcloud_db:
    image: mariadb:10.5
    container_name: nextcloud_db
    hostname: nextcloud_db
    security_opt:
      - no-new-privileges:true
    restart: "unless-stopped"
    profiles: ["media", "all"]
      #command: --transaction-isolation=READ_COMMITTED --log-bin=msqyld-bin --binlog-format=ROW
    networks:
      - default
    ports:
      - "$MARIADB_PORT:3306"
    volumes:
      - ${DOCKERDIR}/appdata/db-nextcloud/data:/var/lib/mysql
      - ${DOCKERDIR}/appdata/db-nextcloud/config:/etc/mysql
    secrets:
      - mariadb_root_password
      - nextcloud_mariadb_password
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      MYSQL_USER: nc-user
      MYSQL_DATABASE: db-nextcloud
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/nextcloud_mariadb_password

