services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
      #user: 33:33
    security_opt:
      - no-new-privileges:true
    restart: "always"
    profiles: ["media", "all"]
    networks:
      - default
    ports:
      - "$OBSIDIAN_PORT:3001"
    volumes:
      - ${DOCKERDIR}/appdata/obsidian:/config
      - ${MEDIADIR}/Documents/nextcloud/hueylaforet/files/Obsidian:/notes
    environment:
      PUID: 33
      PGID: 33
      TZ: $TZ
