services:
  #qBittorrent - Torrent Downloader
  qbittorrent-vpn:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent-vpn
    security_opt:
      - no-new-privileges:true
    restart: always
    profiles: ["apps", "downloads", "all"]
    network_mode: "service:gluetun"
    volumes:
      - $DOCKERDIR/appdata/qbittorrent-vpn:/config
      - $DOWNLOADSDIR/torrent:/data/downloads/torrent
      - $DOCKERDIR/logs/qbittorrent:/logs
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      UMASK_SET: 002
      WEBUI_PORT: $QBITTORRENT_PORT
    healthcheck:
      test: "curl -sf https://example.com || exit 1"
      interval: 1m
      timeout: 10s
      retries: 1
