services:
  redis:
    image: docker.io/library/redis
    container_name: redis
    hostname: redis
    restart: unless-stopped
    user: "$PUID:$PGID"
    security_opt:
      - no-new-privileges:true
    networks:
      - default
    ports:
      - $REDIS_PORT:6379
    volumes:
      - $DOCKERDIR/appdata/redis:/data
        #- $DOCKERDIR/appdata/redis/config:/usr/local/etc/php/
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
