services:
  # Crowdsec Bouncer - Traefik
  traefik-bouncer:
    image: fbonalair/traefik-crowdsec-bouncer
    container_name: traefik-bouncer
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - t3_proxy
      - default
    environment:
      GIN_MODE: debug
      CROWDSEC_BOUNCER_API_KEY: $CROWDSEC_BOUNCER_TRAEFIK_API_KEY
      CROWDSEC_AGENT_HOST: "$SERVER_LAN_IP:$CROWDSEC_PORT"
      CROWDSEC_BOUNCER_LOG_LEVEL: 1
      TZ: "$TZ"
